# Generated by Django 5.2.4 on 2025-07-15 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AIModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(help_text="User-friendly name for the model (e.g., 'Deepseek').", max_length=100, unique=True)),
                ('model_name', models.CharField(help_text="The technical model identifier for the API call (e.g., 'deepseek/deepseek-r1-0528:free').", max_length=100)),
                ('api_provider', models.CharField(choices=[('google_gemini', 'Google Gemini'), ('open_router', 'OpenRouter')], help_text='The service that provides this model.', max_length=50)),
                ('api_key_name', models.CharField(help_text="The name of the environment variable holding the API key (e.g., 'OPENROUTER_API_KEY').", max_length=100)),
                ('is_active', models.BooleanField(default=True, help_text='Enable or disable this model for all users.')),
                ('login_required', models.BooleanField(default=False, help_text='If checked, only logged-in users can use this model.')),
                ('daily_limit', models.PositiveIntegerField(default=0, help_text='Max number of requests per day for a logged-in user. 0 means no limit.')),
                ('response_time_info', models.CharField(blank=True, help_text="Aprox. response time to show to the user (e.g., 'Fast', '5-10 seconds').", max_length=100)),
                ('description', models.TextField(blank=True, help_text='A short description of the model for the user.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['display_name'],
            },
        ),
    ]
